site_name: Plugin-Wordpress
repo_url: https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress

extra_css: 
        - assets/stylesheets/extra.css

theme:
        name: material
        language: pt
        features:
                - navigation.tabs

nav:
        - Home: index.md
        - Atas: 
                - ata modelo: Atas/ata-modelo.md
        - Backlog do produto: backlog.md