site_name: Plugin-Wordpress
repo_url: https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress

extra_css: 
        - assets/stylesheets/extra.css

theme:
        name: material
        language: pt
        features:
                - navigation.tabs

nav:
        - Home: index.md 
        - Preparando ambiente: preparandoambiente.md
        - Atas: 
                - ata modelo: Atas/ata-modelo.md
                - ata reunião 1: Atas/ata-reuniao1.md
                - ata reunião 2: Atas/ata-reuniao2.md
        - Backlog do produto: backlog.md
        - Roadmap: roadmap.md