# Define o nome do site
site_name: LGBTQ+ CONNECT

# Define a URL do repositório do GitHub
repo_url: https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress

# Especifica um arquivo CSS adicional para ser carregado
extra_css: 
  - assets/stylesheets/extra.css

# Define as configurações do tema do material
theme:
  # Define o nome do tema como "material"
  name: material

  # Define o idioma do tema como português
  language: pt

  # Define a logo da página
  favicon: assets/images/logo.png
  logo: assets/images/logo.png
    
  # Lista as características do tema
  features:
    - navigation.tabs  # Adiciona abas de navegação para diferentes seções do site.

  # Define a paleta de cores do tema
  palette:
    # Define o esquema de cores como "default"
    - scheme: default
      # Configura o botão de alternância entre os modos claro e escuro
      toggle:
        # Define o ícone do botão
        icon: material/toggle-switch-off-outline 
        # Define o texto alternativo do botão
        name: Switch to dark mode
      # Define a cor primária do tema
      primary: lime
      # Define a cor de destaque do tema
      accent: lime 

    # Define outro esquema de cores
    - scheme: slate 
      # Configura o botão de alternância entre os modos claro e escuro
      toggle:
        # Define o ícone do botão
        icon: material/toggle-switch
        # Define o texto alternativo do botão
        name: Switch to light mode    
      # Define a cor primária do tema
      primary: lime
      # Define a cor de destaque do tema
      accent: lime  

# Define a navegação do site, especificando os links para diferentes páginas ou seções do site
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - Preparando ambiente: preparandoambiente.md
  - Atas:
      - ata reunião 1: Atas/ata-reuniao1.md
      - ata reunião 2: Atas/ata-reuniao2.md
      - ata reunião 3: Atas/ata-reuniao3.md
      - ata reunião 4: Atas/ata-reuniao4.md
      - ata reunião 5: Atas/ata-reuniao5.md
  - Wireframe: wireframe.md
  - Backlog do produto: backlog.md
  - Arquitetura: arquitetura.md
  - Storymap: storymap.md
  - Roadmap: roadmap.md
  - Releases:
      - Release 1: releases/release1.md
      - Release 2: releases/release2.md
      - Release 3: releases/release3.md