site_name: Plugin-Wordpress
repo_url: https://github.com/ResidenciaTICBrisa/T2G8-Plugin-Wordpress

extra_css: 
        - assets/stylesheets/extra.css


nav:
        - Home: index.md
        - Atas: 
            - ata modelo: ata-modelo.md
        